Parameters:
  GHsecret: 
    Type: String
    Default: Can't_be_empty
Resources:
  GitHubSecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: GitHubSecret
      Description: AWS secrets for GitHub
      SecretString:  '{"Secret": !Ref GHsecret}'
      Tags: 
        - Key: project
          Value: new-product